# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Category.create(name: "Birthday");
Category.create(name: "Wedding");
Category.create(name: "New Baby");
Category.create(name: "Anniversary");
Category.create(name: "Condolences");
Category.create(name: "Xmas/Religious Holiday");
Category.create(name: "Thank You");
Category.create(name: "BF/GF/Spouse");
Category.create(name: "Get Well Soon");
Category.create(name: "General");

GreetingCard.create(title: "You are older now, great", description: "Congratulations, you survived this wreck of a world for another year, what do you want, a bloody medal or something?", category_id: 1, image: "https://i.pinimg.com/736x/e7/76/fd/e776fd031bf7dafcf906c469c3241f51--bad-cakes-cake-wrecks.jpg");
GreetingCard.create(title: "You were born, big deal", description: "Here’s a coconut on the arbitrary day of the year you fell out of the womb, what a champ you are.", category_id: 1, image: "https://stephentong.files.wordpress.com/2008/07/birthday-cake.jpg");
GreetingCard.create(title: "Birthday? More like barfday", description: "Getting older is not necessarily getting wiser, but I do have to say you at least look older, so top marks for consistency at least.", category_id: 1, image: "https://i.huffpost.com/gen/3093010/images/o-VOMIT-BIRTHDAY-CAKE-facebook.jpg");
GreetingCard.create(title: "On this day, your mum did the hard work, not you", description: "Why would anyone celebrate you or your achievements on a day when all you did was kick and scream covered in goo while your mum was in agony? Shame on you.", category_id: 1, image: "https://mylifeandkids.com/wp-content/uploads/2013/10/Birthday-Fail-13.jpg");
GreetingCard.create(title: "Betrothal is betrayal", description: "Commiserations on your loss of freedom, self-identity and financial independence, no doubt your supposed love will buck any and all trends in modern marriage statistics.", category_id: 2, image: "https://1.bp.blogspot.com/-Eqwhdi47O-k/UPjJO4Ydy9I/AAAAAAAAAQA/6mOseibFH80/s1600/bad+wedding+photos+2.jpeg");
GreetingCard.create(title: "One ring to rule all of your weak personality", description: "", category_id: 2, image: "https://www.thethings.com/wp-content/uploads/2016/09/weddingfail.jpg");
GreetingCard.create(title: "I disparage your marriage", description: "May all divorce lawyers everywhere raise a toast to the potential that you and your betrothed represent, you're like a pair of big shiny blank checks, after all.", category_id: 2, image: "https://proxy.duckduckgo.com/iu/?u=http%3A%2F%2Fi.ytimg.com%2Fvi%2FkMLkMonDckY%2Fmaxresdefault.jpg&f=1");
GreetingCard.create(title: "Your wedding won’t cure your loneliness", description: "Latching onto someone to make up for the vacuous abyss at your core is not love, it's clutching at straws at best and straight up energy vampirism at worst.", category_id: 2, image: "http://dz8z45gu0xcif.cloudfront.net/wp-content/uploads/2017/09/19080204/11-horrendous-ugly-wedding-dress-fail-balloon-gown.png");
GreetingCard.create(title: "So you’ve dragged another poor soul into this wretched existence", description: "Well done, you’ve now managed to do what literally every other parent in history managed before you, I'm sure it'll work out better for your child than the countless kids abandoned by a cold and callous world.", category_id: 3, image: "http://cdn2.holytaco.com/wp-content/uploads/2011/01/23-Copy.jpg");
GreetingCard.create(title: "Your new child won’t mask your immaturity", description: "The supposed miracle of birth is nothing but pure biology, putting you on a par with rats, and most amusing, you thought THAT was the hard part.", category_id: 3, image: "https://pbs.twimg.com/profile_images/3046129083/6568686d0ce979063905032718d47007_400x400.jpeg");
GreetingCard.create(title: "How original, a new baby", description: "Many thanks to you for bringing into this world yet another drain on swiftly dwindling resources, you must be so proud of your creativity.", category_id: 3, image: "http://dybiz.com/sites_randomblog/wp-content/uploads/2011/06/ugly_baby400x.jpg");
GreetingCard.create(title: "Congratulations on your lack of contraception", description: "You most certainly deserve lauding for swapping your carefree and joy-filled life for an endless slew of soggy nappies and years' worth of ingratitude and disdain, eventually culminating in the auspicious occasion of your offspring tucking you quietly away into some decrepit care home.", category_id: 3, image: "https://proxy.duckduckgo.com/iu/?u=http%3A%2F%2F1.bp.blogspot.com%2F-6GCi_b5SyaA%2FTfhGQzvSKXI%2FAAAAAAAAADc%2FegXr-PvSaXs%2Fs1600%2Fugly-baby-2.jpg&f=1");
GreetingCard.create(title: "God, you still live with THAT person", description: "It’s quite the achievement that you don’t publicly show your ingrained and rapidly growing mutual resentment, you would make a good pair of spies.", category_id: 4, image: "https://www.blogcdn.com/www.parentdish.co.uk/media/2012/04/fighting-women.jpg");
GreetingCard.create(title: "Another year of toxic cohabitation", description: "Kudos to you both for seeing the rancour through for another year, and on and on to the bitter end against any and all reason.", category_id: 4, image: "https://i2-prod.mirror.co.uk/incoming/article1944026.ece/ALTERNATES/s615/Bored-couple-sitting-on-sofa-not-looking-at-each-other.jpg");
GreetingCard.create(title: "You’re too old to do any better now", description: "It is truly amazing that you fell for each other's sycophantic flattery so many years ago, and on top of that, that you thought whatever minor looks you had would last too.", category_id: 4, image: "https://c8.alamy.com/compde/aj9gd8/zwei-schwule-manner-sitzen-auf-einer-parkbank-aj9gd8.jpg");
GreetingCard.create(title: "I hope the joint bank account was worth it", description: "Let's face it, you were just scared of ending up penniless and alone, and to your credit, you've stuck with it despite the sheer agony of your everyday existence together.", category_id: 4, image: "https://i2.cdn.turner.com/cnn/2011/images/06/02/t1larg.bored.bed.ts.jpg");
GreetingCard.create(title: "Even less impressive than being born is dying", description: "Honestly, wherever that person is now (even if you believe that it’s just in the ground and nothing more) has got to be better than this sideshow attraction of a world.", category_id: 5, image: "http://www.veryhappypig.com/blog/clown-funeral-x.jpg");
GreetingCard.create(title: "Too many mouths to feed anyway", description: "You have no reason to be so downbeat when you consider that the deceased is providing a fine ecological service to the planet - the worms have to eat something, right?", category_id: 5, image: "http://www.x-pressed.org/wp-content/uploads/2014/03/zenica-blog-0.jpg");
GreetingCard.create(title: "You’ll find someone else to leech off", description: "Seriously, throw a rock over your shoulder and you'll hit another, probably better person to take the place of that personality vacuum you just lost.", category_id: 5, image: "http://funny-lover.com/wp-content/uploads/2014/03/wtf-happy-funeral.jpg");
GreetingCard.create(title: "Why are YOU so sad when you’re still alive?", description: "What is it about life that is so precious to you anyway? Think about it, now you can have all of deceased's stuff without having to put up with their incessant blethering.", category_id: 5, image: "https://4.bp.blogspot.com/_JDOjVzS09RM/TEXABaSfz4I/AAAAAAAAG0Q/6Hruc4u_eWE/s1600/happy.jpg");
GreetingCard.create(title: "You’re not mystical, you’re just mistaken", description: "It is both laudable yet laughable that you believe in ghosts to such a degree that you’d spend all year bitching and whining about your job just to wholeheartedly nail your colours to the cross of commerce on some pre-ordained but frankly random day of the year.", category_id: 6, image: "https://i.pinimg.com/originals/cb/59/43/cb5943421ace4e43363f937883b0a7ce.jpg");
GreetingCard.create(title: "Superb job of being just another sheep", description: "Truly, you ought to pat yourself on the back for living like an ecclesiastical serf in a time-warp, and not even having any self-awareness whatsoever about it.", category_id: 6, image: "http://images.dailystar.co.uk/dynamic/1/photos/858000/57858.jpg");
GreetingCard.create(title: "Religion should be last year, not every year", description: "Statues should surely be erected in your honour, given your blinkered adherence to barefaced business masquerading as religion, may your statues be as plastic as the cheapest of trinket-relics you ferverously polish every year.", category_id: 6, image: "https://i.huffpost.com/gen/790456/images/o-152784081-facebook.jpg");
GreetingCard.create(title: "Festive spirit? More like festering spit", description: "I'll cheer up when you bloody well get your humble-bragging, fairweather evangelism out of my face, but until then, don't dare tell me how to feel nor when.", category_id: 6, image: "https://roodepoortrecord.co.za/wp-content/uploads/sites/20/2015/12/1280x720-RYW.jpg");
GreetingCard.create(title: "Gratitude is for attention hogs", description: "You deserve so much credit for helping me with whatever it was you did (I forget), because I am genuinely too lazy, ungrateful and disinterested to do anything of vague importance by myself.", category_id: 7, image: "http://www.mergedesignstudio.com/wp-content/uploads/2017/04/no_thanks-1024x755.png");
GreetingCard.create(title: "So much for selflessness, oh needy one", description: "Should you want proof of my apathy towards you, here is this meaningless card which I hope can some day serve as kindling at your cremation", category_id: 7, image: "https://clipground.com/images/selfishness-clipart-11.jpg");
GreetingCard.create(title: "Good deeds are their own virtue, so here's something crappy", description: "If you want something inherently pointless to cement your smugness about whatever minor feat of assistance you begrudgingly accomplished, here you go.", category_id: 7, image: "https://www.parcelhero.com/blog/wp-content/uploads/sites/3/2016/01/Time-is-running-out-to-return-unwanted-gifts-says-ParcelHero-e1452252208934.jpg");
GreetingCard.create(title: "I’ll thank you when you’ve improved", description: "What a true marvel of nature you are, requiring a pat on the head for making the least bit of effort, so here's something not so much to massage your tiny little ego as to demand more and better from you next time.", category_id: 7, image: "https://theinterviewguys.com/wp-content/uploads/2015/01/no-thank-you-e1421879319938.png");
GreetingCard.create(title: "I have no time to meet new people", description: "Woop-de-doo, you picked me, you actually CHOSE this laughing stock of a relationship, and now you feel trapped but unable to get back out there, yet the saddest part is, I'm exactly the same.", category_id: 8, image: "http://media.philly.com/images/unwanted-touching-istock-600.jpg");
GreetingCard.create(title: "I'm SO glad we settled for each other", description: "Here is incontrovertible proof that you chose extremely poorly when we got together, as did I, but I guess we've made our beds now and must lie in them. Awesome.", category_id: 8, image: "https://catholic-link.com/wp-content/uploads/2016/12/navidad.png");
GreetingCard.create(title: "When we first met, you were Ok", description: "This card stands as a testament to our incredible lack of foresight - the years have done nothing but fill us with contempt, so at least we have that in common.", category_id: 8, image: "https://static.tvtropes.org/pmwiki/pub/images/Unwanted_Spouse_3632.png");
GreetingCard.create(title: "You’ll have to do - for now", description: "It would be easy to criticize you but at the end of the day, I should really criticize myself for my own poor taste in getting together with you, nobody put a gun to my head after all, though I sometimes wish they would now.", category_id: 8, image: "https://i.ytimg.com/vi/uoN2jawTpGU/hqdefault.jpg");
GreetingCard.create(title: "I TOLD you to wrap up warm", description: "If I were you, I would pray to whoever or whatever that you only deteriorate from hereon in, because there’s only one direction we’re all going in anyway.", category_id: 9, image: "https://www.healthhelper.com.au/wp-content/uploads/2016/05/cold-remedies-for-sick-person.jpg");
GreetingCard.create(title: "Aren’t you a sensitive little flower?", description: "I should like to praise you for your consistency in complaining interminably about the minorest of ailments, so if it's really that bad, perhaps it would be the merciful thing to just let yourself drift away?", category_id: 9, image: "https://i.dailymail.co.uk/i/pix/2008/08/01/article-0-021F22E200000578-57_468x286.jpg");
GreetingCard.create(title: "Malingering is not attractive", description: "Everybody has something or other wrong with them, so what makes your whiney noise so special? If you want any sympathy at all, just try keeping your mouthhole shut for five blooming seconds.", category_id: 9, image: "https://1.bp.blogspot.com/-_YMsKsNcr3w/T2uwPD7OtLI/AAAAAAAAARw/1aMiB4lsOKw/s1600/Sick+man.jpg");
GreetingCard.create(title: "What an elaborate way to skip work", description: "Seriously, the innovative and pity-seeking way you've managed to shirk any and all of your most basic responsibilities deserves utmost respect, here's a card to represent that instead of the medicine you claim to need.", category_id: 9, image: "https://thumbs.dreamstime.com/z/throwing-up-closeup-portrait-young-sick-man-funny-looking-boy-sticking-finger-mouth-to-throw-show-something-sucks-38862701.jpg");
GreetingCard.create(title: "Here’s a card to show I couldn’t be bothered", description: "I wasn’t sure you were even worth properly insulting, let alone praising, so here is this lacklustre message which will still no doubt somehow swell your infantile sense of self.", category_id: 10, image: "https://mustbethistalltoride.files.wordpress.com/2014/06/man-shrugging-shoulders.jpg");
GreetingCard.create(title: "This was cheaper than other cards", description: "I couldn't even really be bothered to write anything proper here, because this card is in honour of such a non-event that the effort might have crippled me.", category_id: 10, image: "https://print24.com/de/blog/wp-content/uploads/2013/02/MarkoKubitz_unbeschwert.jpg");
GreetingCard.create(title: "Why am I sending you this again?", description: "I want to give you full and proper credit for being so unutterably forgettable and commonplace that I'm not even sure what it is we're celebrating here.", category_id: 10, image: "https://www.aim.org/wp-content/uploads/2013/08/obama-scratching-head-during-speech.jpg");
GreetingCard.create(title: "I wish you were worthy of more effort than this", description: "This card is an exercise in futility, as has been much of your life - all I can hope for is that this is the last ever interaction between us, and that we can bot forget and move on.", category_id: 10, image: "http://listcrown.com/wp-content/uploads/2013/09/shrugging_shoulders2.jpg");
